[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beanie>=1.29.0",
    "coverage>=7.6.10",
    "fastapi[standard]>=0.115.8",
    "httpx>=0.28.1",
    "mongomock-motor>=0.0.35",
    "passlib>=1.7.4",
    "pydantic-settings>=2.7.1",
    "pytest-asyncio>=0.25.3",
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
    "python-jose>=3.3.0",
    "uvicorn>=0.34.0",
    "email-validator>=2.2.0",
]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
