name: Bandit Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Bandit
      run: pip install bandit
    - name: Run Bandit
      run: bandit -r . -f custom --msg-template "{abspath}:{line}: {severity}: {test_id}: {msg}"
    - name: Upload Bandit Scan Results
      uses: actions/upload-artifact@v2
      with:
        name: bandit-results
        path: bandit-results.txt
